-- MySQL Script generated by MySQL Workbench
-- Tue Mar 12 15:13:56 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema quizz
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `quizz` ;

-- -----------------------------------------------------
-- Schema quizz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quizz` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `quizz` ;

-- -----------------------------------------------------
-- Table `quizz`.`category_course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizz`.`category_course` ;

CREATE TABLE IF NOT EXISTS `quizz`.`category_course` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quizz`.`category_exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizz`.`category_exam` ;

CREATE TABLE IF NOT EXISTS `quizz`.`category_exam` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quizz`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizz`.`roles` ;

CREATE TABLE IF NOT EXISTS `quizz`.`roles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quizz`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizz`.`users` ;

CREATE TABLE IF NOT EXISTS `quizz`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NULL DEFAULT NULL,
  `lastName` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `gender` VARCHAR(255) NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `refreshToken` VARCHAR(255) NULL DEFAULT NULL,
  `roleId` BIGINT NOT NULL DEFAULT '3',
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  INDEX `roleId` (`roleId` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`roleId`)
    REFERENCES `quizz`.`roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quizz`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizz`.`courses` ;

CREATE TABLE IF NOT EXISTS `quizz`.`courses` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `categoryCourseId` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `summary` TEXT NULL DEFAULT NULL,
  `assignedBy` BIGINT NULL DEFAULT NULL,
  `durationInMinute` INT NULL DEFAULT NULL,
  `startDate` DATETIME NULL DEFAULT NULL,
  `endDate` DATETIME NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `locationPath` VARCHAR(255) NULL DEFAULT NULL,
  `prepare` TEXT NULL DEFAULT NULL,
  `price` DECIMAL(15,2) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `categoryCourseId` (`categoryCourseId` ASC) VISIBLE,
  CONSTRAINT `courses_ibfk_1`
    FOREIGN KEY (`categoryCourseId`)
    REFERENCES `quizz`.`category_course` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quizz`.`course_progress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizz`.`course_progress` ;

CREATE TABLE IF NOT EXISTS `quizz`.`course_progress` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `userId` BIGINT NOT NULL,
  `courseId` BIGINT NOT NULL,
  `completionStatus` TINYINT(1) NULL DEFAULT NULL,
  `progressPercentage` FLOAT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `course_progress_courseId_userId_unique` (`userId` ASC, `courseId` ASC) VISIBLE,
  INDEX `courseId` (`courseId` ASC) VISIBLE,
  CONSTRAINT `course_progress_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `quizz`.`users` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `course_progress_ibfk_2`
    FOREIGN KEY (`courseId`)
    REFERENCES `quizz`.`courses` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quizz`.`lessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizz`.`lessions` ;

CREATE TABLE IF NOT EXISTS `quizz`.`lessions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `courseId` BIGINT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `courseId` (`courseId` ASC) VISIBLE,
  CONSTRAINT `lessions_ibfk_1`
    FOREIGN KEY (`courseId`)
    REFERENCES `quizz`.`courses` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quizz`.`exams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizz`.`exams` ;

CREATE TABLE IF NOT EXISTS `quizz`.`exams` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `categoryExamId` BIGINT NOT NULL,
  `lessionId` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `durationInMinute` INT NULL DEFAULT NULL,
  `pointToPass` INT NULL DEFAULT NULL,
  `createrId` BIGINT NULL DEFAULT NULL,
  `numberOfAttempt` TINYINT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `categoryExamId` (`categoryExamId` ASC) VISIBLE,
  INDEX `lessionId` (`lessionId` ASC) VISIBLE,
  CONSTRAINT `exams_ibfk_1`
    FOREIGN KEY (`categoryExamId`)
    REFERENCES `quizz`.`category_exam` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `exams_ibfk_2`
    FOREIGN KEY (`lessionId`)
    REFERENCES `quizz`.`lessions` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quizz`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizz`.`questions` ;

CREATE TABLE IF NOT EXISTS `quizz`.`questions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `instruction` TEXT NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  `a` TEXT NULL DEFAULT NULL,
  `b` TEXT NULL DEFAULT NULL,
  `c` TEXT NULL DEFAULT NULL,
  `d` TEXT NULL DEFAULT NULL,
  `e` TEXT NULL DEFAULT NULL,
  `f` TEXT NULL DEFAULT NULL,
  `g` TEXT NULL DEFAULT NULL,
  `h` TEXT NULL DEFAULT NULL,
  `i` TEXT NULL DEFAULT NULL,
  `j` TEXT NULL DEFAULT NULL,
  `k` TEXT NULL DEFAULT NULL,
  `l` TEXT NULL DEFAULT NULL,
  `m` TEXT NULL DEFAULT NULL,
  `n` TEXT NULL DEFAULT NULL,
  `o` TEXT NULL DEFAULT NULL,
  `p` TEXT NULL DEFAULT NULL,
  `answer` TEXT NULL DEFAULT NULL,
  `explanation` TEXT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quizz`.`exams_questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizz`.`exams_questions` ;

CREATE TABLE IF NOT EXISTS `quizz`.`exams_questions` (
  `examId` BIGINT NOT NULL,
  `questionId` BIGINT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`examId`, `questionId`),
  UNIQUE INDEX `exams_questions_questionId_examId_unique` (`examId` ASC, `questionId` ASC) VISIBLE,
  INDEX `questionId` (`questionId` ASC) VISIBLE,
  CONSTRAINT `exams_questions_ibfk_1`
    FOREIGN KEY (`examId`)
    REFERENCES `quizz`.`exams` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `exams_questions_ibfk_2`
    FOREIGN KEY (`questionId`)
    REFERENCES `quizz`.`questions` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quizz`.`lession_document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizz`.`lession_document` ;

CREATE TABLE IF NOT EXISTS `quizz`.`lession_document` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `lessionId` BIGINT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `completed` TINYINT(1) NOT NULL DEFAULT '0',
  `order` BIGINT NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `locationPath` VARCHAR(255) NOT NULL,
  `createdBy` BIGINT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `lessionId` (`lessionId` ASC) VISIBLE,
  CONSTRAINT `lession_document_ibfk_1`
    FOREIGN KEY (`lessionId`)
    REFERENCES `quizz`.`lessions` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quizz`.`lession_pdf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizz`.`lession_pdf` ;

CREATE TABLE IF NOT EXISTS `quizz`.`lession_pdf` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `lessionId` BIGINT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `completed` TINYINT(1) NOT NULL DEFAULT '0',
  `order` BIGINT NOT NULL,
  `locationPath` VARCHAR(255) NOT NULL,
  `uploadedBy` BIGINT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `lessionId` (`lessionId` ASC) VISIBLE,
  CONSTRAINT `lession_pdf_ibfk_1`
    FOREIGN KEY (`lessionId`)
    REFERENCES `quizz`.`lessions` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quizz`.`lession_video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizz`.`lession_video` ;

CREATE TABLE IF NOT EXISTS `quizz`.`lession_video` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `lessionId` BIGINT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `completed` TINYINT(1) NOT NULL DEFAULT '0',
  `order` BIGINT NOT NULL,
  `locationPath` VARCHAR(255) NOT NULL,
  `uploadedBy` BIGINT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `lessionId` (`lessionId` ASC) VISIBLE,
  CONSTRAINT `lession_video_ibfk_1`
    FOREIGN KEY (`lessionId`)
    REFERENCES `quizz`.`lessions` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quizz`.`permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizz`.`permission` ;

CREATE TABLE IF NOT EXISTS `quizz`.`permission` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quizz`.`question_discussion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizz`.`question_discussion` ;

CREATE TABLE IF NOT EXISTS `quizz`.`question_discussion` (
  `userId` BIGINT NOT NULL,
  `questionId` BIGINT NOT NULL,
  `comment` TEXT NOT NULL,
  `like` INT NULL DEFAULT NULL,
  `unlike` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`userId`, `questionId`),
  UNIQUE INDEX `question_discussion_questionId_userId_unique` (`userId` ASC, `questionId` ASC) VISIBLE,
  INDEX `questionId` (`questionId` ASC) VISIBLE,
  CONSTRAINT `question_discussion_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `quizz`.`users` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `question_discussion_ibfk_2`
    FOREIGN KEY (`questionId`)
    REFERENCES `quizz`.`questions` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quizz`.`role_to_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizz`.`role_to_permission` ;

CREATE TABLE IF NOT EXISTS `quizz`.`role_to_permission` (
  `roleId` BIGINT NOT NULL,
  `permissionId` BIGINT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`roleId`, `permissionId`),
  UNIQUE INDEX `role_to_permission_permissionId_roleId_unique` (`roleId` ASC, `permissionId` ASC) VISIBLE,
  UNIQUE INDEX `role_to_permission_role_id_permission_id` (`roleId` ASC, `permissionId` ASC) VISIBLE,
  INDEX `permissionId` (`permissionId` ASC) VISIBLE,
  CONSTRAINT `role_to_permission_ibfk_1`
    FOREIGN KEY (`roleId`)
    REFERENCES `quizz`.`roles` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `role_to_permission_ibfk_2`
    FOREIGN KEY (`permissionId`)
    REFERENCES `quizz`.`permission` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quizz`.`temp_users_answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizz`.`temp_users_answer` ;

CREATE TABLE IF NOT EXISTS `quizz`.`temp_users_answer` (
  `userId` BIGINT NOT NULL,
  `examId` BIGINT NOT NULL,
  `questionId` BIGINT NOT NULL,
  `userAnswer` TEXT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`userId`, `examId`, `questionId`),
  INDEX `examId` (`examId` ASC) VISIBLE,
  INDEX `questionId` (`questionId` ASC) VISIBLE,
  CONSTRAINT `temp_users_answer_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `quizz`.`users` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `temp_users_answer_ibfk_2`
    FOREIGN KEY (`examId`)
    REFERENCES `quizz`.`exams` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `temp_users_answer_ibfk_3`
    FOREIGN KEY (`questionId`)
    REFERENCES `quizz`.`questions` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quizz`.`user_enter_exit_exam_room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizz`.`user_enter_exit_exam_room` ;

CREATE TABLE IF NOT EXISTS `quizz`.`user_enter_exit_exam_room` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `userId` BIGINT NOT NULL,
  `examId` BIGINT NOT NULL,
  `enterTime` DATETIME NOT NULL,
  `exitTime` DATETIME NULL DEFAULT NULL,
  `attempt` TINYINT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  UNIQUE INDEX `user_enter_exit_exam_room_examId_userId_unique` (`userId` ASC, `examId` ASC) VISIBLE,
  INDEX `examId` (`examId` ASC) VISIBLE,
  CONSTRAINT `user_enter_exit_exam_room_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `quizz`.`users` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `user_enter_exit_exam_room_ibfk_2`
    FOREIGN KEY (`examId`)
    REFERENCES `quizz`.`exams` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quizz`.`users_answer_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizz`.`users_answer_history` ;

CREATE TABLE IF NOT EXISTS `quizz`.`users_answer_history` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `attempt` TINYINT NOT NULL,
  `userId` BIGINT NOT NULL,
  `examId` BIGINT NOT NULL,
  `questionId` BIGINT NOT NULL,
  `userAnswer` TEXT NULL DEFAULT NULL,
  `score` TINYINT NULL DEFAULT NULL,
  `isCorrect` TINYINT(1) NULL DEFAULT NULL,
  `overAllScore` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC) VISIBLE,
  INDEX `userId` (`userId` ASC) VISIBLE,
  INDEX `examId` (`examId` ASC) VISIBLE,
  INDEX `questionId` (`questionId` ASC) VISIBLE,
  CONSTRAINT `users_answer_history_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `quizz`.`users` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `users_answer_history_ibfk_2`
    FOREIGN KEY (`examId`)
    REFERENCES `quizz`.`exams` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `users_answer_history_ibfk_3`
    FOREIGN KEY (`questionId`)
    REFERENCES `quizz`.`questions` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
